stages:          # List of stages for jobs, and their order of execution
  - build
  - review
  - cleanup
  - production

include:
  # Docker Build
  - template: Docker.gitlab-ci.yml
  # Enable ArgoCD Deployment
  - project: 'madou-stories/gitlab-ci-catalog'
    ref: main
    file: '/ArgoCD/Deploy.gitlab-ci.yml'
  
