# Enable Merge Request Pipeline
workflow: &workflow_mr
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# List of stages for jobs, and their order of execution 
stages:
  - build
  - review
  - cleanup
  - production

include:
  # Docker Build
  - template: Docker.gitlab-ci.yml
  # Enable ArgoCD Deployment
  - project: 'madou-stories/gitlab-ci-catalog'
    ref: main
    file: '/ArgoCD/Deploy.gitlab-ci.yml'
  
